### ISSUE TITLE
ONIX - MARCH 1 Milestone

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#35]
## Description

Here we will be list milestones for tasks for March-1.

## Goals

- [ ] ONIX installer should execute successfully on the Server instances with OS - Ubuntu 20+ LTI , Amazon Linux and Cent OS. If any dependency is not there it should install the dependencies also ex- Docker,git.
- [ ] ONIX installer should execute successfully on local system (laptop/desktop) with OS - Windows 10+ , Linux and MAC OS. If any dependency is missing it should install by itself or if not possible should check initially and stop with an error message - pre-requisite check fail.
- [ ] ONIX installer should be able to run for 

1.      All components should install in one go without asking for any input from the user.
2.      User can install specific components with default config - Gatewy+Registry , BAP , BPP , BPP with sandbox.
3.      User can install specific components with custom config - Gatewy+Registry , BAP , BPP , BPP with sandbox.

## Expected Outcome

NA

## Acceptance Criteria

NA

## Implementation Details

NA

## Mockups / Wireframes

NA
---

### Product Name

NA

### Project Name

NA

### Organization Name:

NA

### Domain

NA

### Tech Skills Needed:

NA

### Complexity

NA

### Category

NA

### Sub Category
NA
